#!/usr/bin/env bash

# Check for required arguments
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Strict host key checking disabled (caution!)
ssh -o StrictHostKeyChecking=no -i "$ssh_key" "$username@$server_ip" "mkdir -p ~/"

# Transfer the file
scp -i "$ssh_key" "$file_path" "$username@$server_ip:~/"

echo "File $file_path transferred successfully."

exit 0

